common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from common import views
app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mywebsite/', include('mywebsite.urls')),
    path('', include('mywebsite.urls')),
    path('common/', include('common.urls')),
    path('qnasite/', include('qnasite.urls'))
]

newwl/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index),
]

pybo/urls.py
from django.urls import path

from .views import base_views, answer_views, question_views
app_name = 'pybo'

urlpatterns =[
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
]

newwl/models.py
from django.db import models

# Create your models here.

newwl/views.py
from django.shortcuts import render, redirect

def index(request):
    return render(request, 'newwl/newtem.html')

templates/newwl/newtem.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css?aaa" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>newsite</title>
</head>
<body>
<!-- Fixed navbar -->
<nav class="navbar navbar-expand-sm navbar-light bg-light p-3">
<div class="container-fluid">
  <div class="navbar-header">
    <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
    <a class="navbar-brand" href="#">
      <span class="navbar-toggler-icon" onclick="openSideNav()"></span>
    </a>
  </div>
  <button class="navbar-toggler collapsed" type="button"
          data-bs-toggle="collapse"
          data-bs-target="#sidebarNavDropdown"
          aria-controls="sidebarNavDropdown"
          aria-expanded="false"
          aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
  <div class=" collapse navbar-collapse" id="sidebarNavDropdown">
    <ul class="navbar-nav ms-auto ">
      <li class="nav-item" id="usermessage">
        {% if user.is_authenticated %}
        {{ user.username }}님 환영합니다.
        {% endif %}
      </li>
      <li class="nav-item">
        {% if user.is_authenticated %}
        <a href="{% url 'common:logout' %}" class="nav-link">로그아웃</a>
        {% else %}
        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
        {% endif %}
      </li>
      <li class="nav-item">
        {% if not user.is_authenticated %}
        <a href="{% url 'common:signup' %}" class="nav-link">회원가입</a>
        {% else %}
        <a href="#" class="nav-link">마이페이지</a>
        {% endif %}
      </li>
<!--      <li class="nav-item dropdown">-->
<!--        <a class="nav-link mx-2 dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">-->
<!--          Company-->
<!--        </a>-->
<!--        <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">-->
<!--          <li><a class="dropdown-item" href="#">Blog</a></li>-->
<!--          <li><a class="dropdown-item" href="#">About Us</a></li>-->
<!--          <li><a class="dropdown-item" href="#">Contact us</a></li>-->
<!--        </ul>-->
<!--      </li>-->
    </ul>
  </div>
</div>
</nav>
<div id="mySidenav" class="sidenav">
  <a href="javascript:void(0)" class="closebtn" onclick="closeNav()">&times;</a>
  <a href="#">국어 게시판</a>
  <a href="#">영어 게시판</a>
  <a href="#">수학 게시판</a>
  <a href="#">사회탐구 게시판</a>
  <a href="#">과학탐구 게시판</a>
</div>
<!-- Bootstrap JS -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
<!-- Javascript -->
<script type='text/javascript'>
function openSideNav() {
    document.getElementById("mySidenav").style.width = "250px";}
function closeNav() {
    document.getElementById("mySidenav").style.width = "0";
}
</script>
{% block script %}
{% endblock %}
</body>
</html>