common/urls.py
from django.contrib.auth import views as auth_views
from django.urls import path
from common import views
app_name = 'common'
urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
]

config/urls.py
from django.contrib import admin
from django.urls import path
from django.urls import include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('mywebsite/', include('mywebsite.urls')),
    path('', include('mywebsite.urls')),
    path('common/', include('common.urls')),
    path('qnasite/', include('qnasite.urls'))
]

mywebsite/urls.py
from django.contrib import admin
from django.urls import path
from .views import answer_views, base_views, question_views

app_name = 'mywebsite'
urlpatterns = [
    path('admin/', admin.site.urls, name="admin"),
    path('', base_views.index, name="index"),
    path('<int:question_id>', base_views.detail, name="detail"),
    path('answer/create/<int:question_id>', answer_views.answer_create, name='answer_create'),
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>', question_views.question_modify, name='question_modify'),
    path('answer/modify/<int:answer_id>', answer_views.answer_modify, name='answer_modify'),
    path('question/delete/<int:question_id>', question_views.question_delete, name='question_delete'),
    path('answer/delete/<int:answer_id>', answer_views.answer_delete, name='answer_delete'),
    path('question/vote/<int:question_id>', question_views.question_vote, name='question_vote'),
]

pybo/urls.py
from django.urls import path

from .views import base_views, answer_views, question_views
app_name = 'pybo'

urlpatterns =[
    path('', base_views.index, name='index'),
    path('<int:question_id>/', base_views.detail, name='detail'),
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
]

mywebsite/models.py
from django.contrib.auth.models import User
from django.db import models


class Question(models.Model):
    subject = models.CharField(max_length=200)
    content = models.TextField()
    create_date = models.DateTimeField()
    address = models.TextField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    question_modify = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_question')

class Answer(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField()
    create_date = models.DateTimeField()
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    answer_modify = models.DateTimeField(null=True, blank=True)

mywebsite/forms.py
from mywebsite.models import Question, Answer
from django import forms


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['subject', 'content', 'address']

        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']

        widgets = {
            'subject': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10}),
        }

mywebsite/views/answer_views.py
from django.contrib import messages
from django.http import HttpResponseRedirect
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from mywebsite.forms import AnswerForm
from mywebsite.models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    form = AnswerForm(request.POST)
    if form.is_valid():
        answer = form.save(commit=False)
        answer.create_date = timezone.now()
        answer.question = question
        answer.author = request.user
        answer.save()
        return redirect(f"{resolve_url('mywebsite:detail', question_id=question.id)}#answer_{answer.id}")
    context = {'form': form, 'question': question}
    return render(request, 'mywebsite/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages(request, "수정권한이 없습니다.")
        return redirect('mywebsite:detail', question_id=answer.question.id)

    if request.method == 'POST':
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.create_date = timezone.now()
            answer.author = request.user
            answer.save()
            return redirect(f"{resolve_url('mywebsite:detail', question_id=answer.question.id)}#answer_{answer.id}")

    else:
        form = AnswerForm(instance=answer)
    context = {'form': form, 'answer': answer}
    return render(request, 'mywebsite/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages(request, "삭제권한이 없습니다")
    else:
        answer.delete()
    return redirect('mywebsite:detail', question_id=answer.question.id)

mywebsite/views/base_views.py
from django.core.paginator import Paginator
from django.db.models import Q
from django.shortcuts import render

from mywebsite.models import Question


def index(request):
    page = request.GET.get("page", 1)
    kw = request.GET.get("kw", '')
    question_list = Question.objects.order_by('create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |
            Q(content__icontains=kw) |
            Q(answer__content__icontains=kw) |
            Q(author__username__icontains=kw) |
            Q(answer__author__username__icontains=kw)
        ).distinct()
    paginator = Paginator(question_list, 15)
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj}
    return render(request, 'mywebsite/question_list.html', context)


def detail(request, question_id):
    if request.method == "POST":
        pass
    else:
        question = Question.objects.get(id=question_id)
        return render(request, 'mywebsite/question_detail.html', {'question': question})

mywebsite/views/question_views.py
from django.contrib import messages
from django.utils import timezone
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from mywebsite.forms import QuestionForm
from mywebsite.models import Question


@login_required(login_url='common:login')
def question_create(request):
    if request.method == "POST":
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.create_date = timezone.now()
            question.author = request.user
            question.save()
            return redirect('mywebsite:index')
    else:
        form = QuestionForm()
    return render(request, 'mywebsite/question_form.html', {'form': form})


@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, "수정권한이 없습니다.")
        return redirect('mywebsite:detail', question_id=question.id)
    if request.method == "POST":  # 수정하기 눌러서 form 받은후에 서버로 다시 넘어왔을때
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('mywebsite:index')
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'mywebsite/question_form.html', context)


@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages(request, "삭제권한이 없습니다")
        return redirect("mywebsite:detail", question_id=question.id)
    question.delete()
    return redirect('mywebsite:index')


@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, "본인글에는 좋아요를 누를수없습니다")
    else:
        question.voter.add(request.user)
    return redirect("mywebsite:detail", question_id=question.id)

pybo/views/answer_views.py
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from ..models import Question, Answer
from ..forms import AnswerForm

@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    context = {'question': question, 'form':form}
    return render(request, 'pybo/question_detail.html', context)

@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)

@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)

@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user == answer.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))

pybo/views/base_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.core.paginator import Paginator
from ..models import Question
from django.db.models import Q

def index(request):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    question_list = Question.objects.order_by('-create_date')
    if kw:
        question_list = question_list.filter(
            Q(subject__icontains=kw) |  # 제목 검색
            Q(content__icontains=kw) |  # 내용 검색
            Q(answer__content__icontains=kw) |  # 답변 내용 검색
            Q(author__username__icontains=kw) |  # 질문 글쓴이 검색
            Q(answer__author__username__icontains=kw)  # 답변 글쓴이 검색
        ).distinct()
    paginator = Paginator(question_list, 10)
    page_obj = paginator.get_page(page)
    context = {'question_list': page_obj, 'page': page, 'kw': kw}
    return render(request, 'pybo/question_list.html', context)


def detail(request, question_id):
    question = Question.objects.get(id=question_id)
    context = {'question': question}
    return render(request, 'pybo/question_detail.html', context)

pybo/views/question_views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.contrib import messages
from django.utils import timezone
from ..models import Question, Answer
from ..forms import QuestionForm

@login_required(login_url='common:login')
def question_create(request):
    if request.method == 'POST':
        form = QuestionForm(request.POST)
        if form.is_valid():
            question = form.save(commit=False)
            question.author = request.user
            question.create_date = timezone.now()
            question.save()
            return redirect('pybo:index')
    else:
        form = QuestionForm()
        context = {'form':form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_modify(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '수정 권한이 없습니다.')
        return redirect('pybo:detail', question_id=question.id)
    if request.method == "POST":
        form = QuestionForm(request.POST, instance=question)
        if form.is_valid():
            question = form.save(commit=False)
            question.modify_date = timezone.now()
            question.save()
            return redirect('pybo:detail', question_id=question.id)
    else:
        form = QuestionForm(instance=question)
    context = {'form': form}
    return render(request, 'pybo/question_form.html', context)

@login_required(login_url='common:login')
def question_delete(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user != question.author:
        messages.error(request, '삭제권한이 없습니다')
        return redirect('pybo:detail', question_id=question.id)
    question.delete()
    return redirect('pybo:index')

@login_required(login_url='common:login')
def question_vote(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.user == question.author:
        messages.error(request, '본인이 작성한 글은 추천할 수 없습니다.')
    else:
        question.voter.add(request.user)
    return redirect('pybo:detail', question_id=question.id)

qnasite/views/base_views.py
from django.shortcuts import render


def index(request):
    
    return render(request, 'qnasite/base.html')

templates/mywebsite/answer_form.html
{% extends 'mywebsite/base.html' %}
{% block content %}
<!-- 답변 수정-->
<div class="container my-3">
    <form method="post">
        {% csrf_token %}
        {% include "common/form_errors.html" %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea class="form-control" name="content" id="content"
                      rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
        </div>
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>
{% endblock %}

templates/mywebsite/base.html
{% load static %}
<!doctype html>
<html lang="ko">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- mywebsite CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <title>Hello, students!</title>
</head>
<body>

<!-- 네비게이션바 -->
{% include "mywebsite/navbar.html" %}
<!-- 기본 템플릿 안에 삽입될 내용 Start -->
{% block content %}
{% endblock %}
<!-- 기본 템플릿 안에 삽입될 내용 End -->
<!-- Bootstrap JS -->
<script src="{% static 'bootstrap.min.js' %}"></script>
<!-- 자바스크립트 Start -->
{% block script %}
{% endblock %}
<!-- 자바스크립트 End -->
</body>
</html>

templates/mywebsite/navbar.html
<nav class="navbar navbar-expand-lg navbar-light bg-light border-bottom">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'mywebsite:index' %}">mywebsite</a>
        <button class="navbar-toggler" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:logout' %}">{{user.username}} 로그아웃</a>
                    {% else %}
                        <a class="nav-link" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li>
                    {% if not user.is_authenticated %}
                        <a class="nav-link" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
            </ul>
        </div>
    </div>
</nav>

templates/mywebsite/question_detail.html
{% extends 'mywebsite/base.html' %}
{% block content %}
<div class="container my-3">
    <!-- message 표시 -->
    {% if messages %}
    <div class="alert alert-danger my-3" role="alert">
        {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul>
            <li>{{ message.message }}</li>
        </ul>
        {% endfor %}
    </div>
    {% endif %}
    <!-- 질문 -->
    <h2 class="border-bottom py-2">{{ question.subject }}</h2>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ question.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ question.author }}
                </div>
                <div class="badge bg-light text-dark p-2">
                    {{ question.create_date }}
                </div>
            </div>
        </div>
        <div class="my-3">
            <a href="javascript:void(0)" data-uri="{% url 'mywebsite:question_vote' question.id  %}"
               class="recommend btn btn-sm btn-outline-secondary"> 추천
                <span class="badge rounded-pill bg-success">{{question.voter.count}}</span>
            </a>
            {% if request.user == question.author %}
            <a href="{% url 'mywebsite:question_modify' question.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'mywebsite:question_delete' question.id  %}">삭제</a>
            {% endif %}
        </div>
    </div>
    <!-- 답변 -->
    <h5 class="border-bottom my-3 py-2">{{question.answer_set.count}}개의 답변이 있습니다.</h5>
    {% for answer in question.answer_set.all %}
    <a id="answer_{{ answer.id }}"></a>
    <div class="card my-3">
        <div class="card-body">
            <div class="card-text" style="white-space: pre-line;">{{ answer.content }}</div>
            <div class="d-flex justify-content-end">
                <div class="badge bg-light text-dark p-2">
                    {{ answer.author }}
                </div>
                <div class="badge bg-light text-dark p-2">
                    {{ answer.create_date }}
                </div>
            </div>
        </div>
        <div class="my-3">
            {% if request.user == answer.author %}
            <a href="{% url 'mywebsite:answer_modify' answer.id  %}"
               class="btn btn-sm btn-outline-secondary">수정</a>
            <a href="javascript:void(0)" class="delete btn btn-sm btn-outline-secondary "
               data-uri="{% url 'mywebsite:answer_delete' answer.id  %}">삭제</a>
            {% endif %}
        </div>
    </div>
    {% endfor %}
    <!-- 답변 등록 -->
    <form action="{% url 'mywebsite:answer_create' question.id %}" method="post" class="my-3">
        {% csrf_token %}
        <div class="mb-3">
            <label for="content" class="form-label">답변내용</label>
            <textarea {% if not user.is_authenticated %}disabled{% endif %}
                      name="content" id="content" class="form-control" rows="10"></textarea>
        </div>
        <input type="submit" value="답변등록" class="btn btn-primary">
    </form>
</div>
{% endblock %}
{% block script %}
<script type='text/javascript'>
const delete_elements = document.getElementsByClassName("delete");
Array.from(delete_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 삭제하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});
const recommend_elements = document.getElementsByClassName("recommend");
Array.from(recommend_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        if(confirm("정말로 추천하시겠습니까?")) {
            location.href = this.dataset.uri;
        };
    });
});

</script>
{% endblock %}

templates/mywebsite/question_form.html
{% extends 'mywebsite/base.html' %}
{% block content %}
<div class="container">
    <h5 class="my-3 border-bottom pb-2">질문등록</h5>
    <form method="post">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit" class="btn btn-primary">저장하기</button>
    </form>
</div>


{% endblock %}

templates/mywebsite/question_list.html
{% extends 'mywebsite/base.html' %}
{% block content %}

<div class="container">
    <div class="question_list_area">
        <div class="row my-3">
            <div class="col-6">
                <a href="{% url 'mywebsite:question_create' %}" class="btn btn-primary">질문 등록하기</a>
            </div>
            <div class="col-6">
                <div class="input-group">
                    <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                    <div class="input-group-append">
                        <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                    </div>
                </div>
            </div>
        </div>
        <table class="table">
            <thead>
            <tr style="background:#eee;">
                <th style="width: 8%">번호</th>
                <th style="width: 62%">제목</th>
                <th style="width: 10%">작성자</th>
                <th style="width: 20%">작성일시</th>
            </tr>
            </thead>
            <tbody>
            {% if question_list %}
            {% for question in question_list %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td>
                    <a href="{% url 'mywebsite:detail' question.id %}">{{ question.subject }}</a>
                    {% if question.answer_set.count > 0 %}
                    <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                    {% endif %}
                </td>
                <td>{{question.author}}</td>
                <td>{{ question.create_date }}</td>
            </tr>
            {% endfor %}
            {% else %}
            <tr>
                <td colspan="3">질문이 없습니다.</td>
            </tr>
            {% endif %}
            </tbody>
        </table>
        <!-- 페이징처리 시작 -->
        <ul class="pagination justify-content-center">
            <!-- 이전페이지 -->
            {% if question_list.has_previous %}
            <li class="page-item">
                <a class="page-link" data-page="{{ question_list.previous_page_number }}"
                   href="javascript:void(0)">이전</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">이전</a>
            </li>
            {% endif %}
            <!-- 페이지리스트 -->
            {% for page_number in question_list.paginator.page_range %}
            {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
            {% if page_number == question_list.number %}
            <li class="page-item active" aria-current="page">
                <a class="page-link" data-page="{{ page_number }}"
                   href="javascript:void(0)">{{ page_number }}</a>
            </li>
            {% else %}
            <li class="page-item">
                <a class="page-link" data-page="{{page_number}}"
                   href="javascript:void(0)">{{ page_number }}</a>
            </li>
            {% endif %}
            {% endif %}
            {% endfor %}
            <!-- 다음페이지 -->
            {% if question_list.has_next %}
            <li class="page-item">
                <a class="page-link" data-page="{{question_list.next_page_number}}"
                   href="javascript:void(0)">다음</a>
            </li>
            {% else %}
            <li class="page-item disabled">
                <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
            </li>
            {% endif %}
        </ul>
        x
        <!-- 페이징처리 끝 -->
        <form id="searchForm" method="get" action="{% url 'mywebsite:index' %}">
            <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
            <input type="hidden" id="page" name="page" value="{{ page }}">
        </form>
    </div>
    <div class="sidebar"></div>
    <div class="blank-area1"></div>
    <div class="blank-area-2"></div>
    <div class="blank-area3"></div>
    <div class="blank-area4"></div>
</div>
{% block script %}
{% endblock %}
<script type='text/javascript'>
const page_elements = document.getElementsByClassName("page-link");
Array.from(page_elements).forEach(function(element) {
    element.addEventListener('click', function() {
        document.getElementById('page').value = this.dataset.page;
        document.getElementById('searchForm').submit();
    });
});
const btn_search = document.getElementById("btn_search");
btn_search.addEventListener('click', function() {
    document.getElementById('kw').value = document.getElementById('search_kw').value;
    document.getElementById('page').value = 1;  // 검색버튼을 클릭할 경우 1페이지부터 조회한다.
    document.getElementById('searchForm').submit();
});
</script>
{% endblock %}